# Generated by Django 6.0.3 on 2026-03-13 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Madeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Espécie (ex: Pinus Taeda)')),
                ('f_c0k', models.FloatField(verbose_name='Compressão Paralela (fc0,k) [MPa]')),
                ('f_t0k', models.FloatField(verbose_name='Tração Paralela (ftn,k) [MPa]')),
                ('f_v0k', models.FloatField(verbose_name='Cisalhamento (fv0,k) [MPa]')),
                ('f_fe', models.FloatField(verbose_name='Embutimento (fe)')),
                ('f_c90k', models.FloatField(verbose_name='Compressão Normal (fcn,k) [MPa]')),
                ('e_c0m', models.FloatField(verbose_name='Módulo de Elasticidade (Ecn0,m) [MPa]')),
                ('f_fd', models.FloatField(verbose_name='Flexão')),
            ],
            options={
                'verbose_name': 'Madeira',
                'verbose_name_plural': 'Madeiras',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Projeto ou Exercício')),
                ('classe_carregamento', models.CharField(choices=[('permanente', 'Permanente'), ('longa', 'Longa Duração'), ('media', 'Média Duração'), ('curta', 'Curta Duração'), ('instantanea', 'Instantânea')], max_length=20)),
                ('classe_umidade', models.IntegerField(choices=[(1, 'Classe 1 (≤ 12%)'), (2, 'Classe 2 (15%)'), (3, 'Classe 3 (18%)'), (4, 'Classe 4 (≥ 21%)')])),
                ('categoria_madeira', models.IntegerField(default=2, verbose_name='Categoria da Madeira (1, 2 ou 3)')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
        migrations.CreateModel(
            name='PecaDimensionada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=100, verbose_name='Nome da Peça (ex: Viga V1)')),
                ('tipo_esforco', models.CharField(choices=[('tracao', 'Tração Paralela'), ('compressao', 'Compressão Paralela')], max_length=20)),
                ('base_b', models.FloatField(verbose_name='Base da Seção b [cm]')),
                ('altura_h', models.FloatField(verbose_name='Altura da Seção h [cm]')),
                ('comprimento_flambagem', models.FloatField(blank=True, null=True, verbose_name='Comprimento de Flambagem L0 [cm] (Apenas Compressão)')),
                ('forca_solicitante_nd', models.FloatField(verbose_name='Força Atuante Nd [kN]')),
                ('madeira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dimensionamento.madeira')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='dimensionamento.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Ligacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('largura_entalhe_be', models.FloatField(blank=True, null=True, verbose_name='Largura do Entalhe be [cm] (Apenas Entalhe)')),
                ('identificacao', models.CharField(max_length=100, verbose_name='Nome da Ligação (ex: Nó da Treliça)')),
                ('tipo_ligacao', models.CharField(choices=[('pino', 'Pino Metálico/Prego/Parafuso'), ('entalhe', 'Entalhe (Cisalhamento)')], max_length=20)),
                ('forca_cortante_vd', models.FloatField(verbose_name='Força Cortante Vd [kN]')),
                ('diametro_pino', models.FloatField(blank=True, null=True, verbose_name='Diâmetro do Pino d [cm] (Se aplicável)')),
                ('espessura_t1', models.FloatField(blank=True, null=True, verbose_name='Espessura t1 [cm] (Se aplicável)')),
                ('comprimento_corte_entalhe', models.FloatField(blank=True, null=True, verbose_name='Comprimento de Corte [cm] (Apenas Entalhe)')),
                ('madeira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dimensionamento.madeira')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligacoes', to='dimensionamento.projeto')),
            ],
        ),
    ]
